import { NextResponse } from "next/server";
import { z } from "zod";
import { openai } from "@/lib/openai";

const SectionSchema = z.object({
  text: z.string(),
  aiLikelihood: z.enum(["LOW", "MEDIUM", "HIGH"]),
  reason: z.string(),
});

const DetectionSchema = z.object({
  aiProbability: z.number(),
  level: z.enum(["LOW", "MEDIUM", "HIGH"]),
  reason: z.string(),
  flagged: z.array(z.string()),
  recommendation: z.string(),
  sections: z.array(SectionSchema),
});

type DetectionResult = z.infer<typeof DetectionSchema>;

export async function POST(req: Request) {
  try {
    const { text } = await req.json();

    if (!text?.trim()) {
      return NextResponse.json({ error: "text is required" }, { status: 400 });
    }

    const completion = await openai.chat.completions.create({
      model: "gpt-4.1",
      response_format: { type: "json_object" },
      messages: [
        {
          role: "system",
          content:
            "You are an academic integrity assistant. " +
            "You estimate whether text may have been AI-assisted. " +
            "Be conservative with accusations, but when the text clearly matches AI patterns, " +
            "you MUST reflect that with a HIGH probability. " +
            "Do NOT treat simple good writing as AI; focus on telltale patterns: " +
            "repetitive structure, generic filler phrases, sudden topic jumps, " +
            "overly polished yet shallow explanations, or contradictions. " +
            "Always respond with a single JSON object only.",
        },
        {
          role: "user",
          content: `
TEXT TO ANALYZE (student writing):
${text}

TASK:
1. Estimate the overall probability that this text was generated by AI.
2. Identify specific suspicious sections (sentences or short spans).
   - Choose at most 5 sections.
   - Sections must be DISTINCT and NON-OVERLAPPING.
   - Do NOT repeat the same sentence or span in multiple sections.
3. For each suspicious section, return:
   - "text": the exact text span,
   - "aiLikelihood": "LOW" | "MEDIUM" | "HIGH",
   - "reason": a short explanation.

SCALE FOR aiProbability (0 to 1), which will be shown as a percentage:
- 0.00–0.25  (0–25%): LOW — likely human or lightly assisted.
- 0.25–0.60 (25–60%): MEDIUM — mixed / uncertain signals.
- 0.60–1.00 (60–100%): HIGH — strong indications of AI-style text.

Return ONLY valid JSON in this format:
{
  "aiProbability": number,
  "level": "LOW | MEDIUM | HIGH",
  "reason": "string",
  "flagged": ["string"],
  "recommendation": "string",
  "sections": [
    {
      "text": "string",
      "aiLikelihood": "LOW | MEDIUM | HIGH",
      "reason": "string"
    }
  ]
}
          `,
        },
      ],
    });

    const raw = completion.choices[0]?.message?.content ?? "{}";

    let parsed: DetectionResult;
    try {
      parsed = DetectionSchema.parse(JSON.parse(raw));
    } catch {
      parsed = {
        aiProbability: 0,
        level: "LOW",
        reason: "Unable to parse model output.",
        flagged: [],
        recommendation: "Parsing failed or schema mismatch.",
        sections: [],
      };
    }

    const seen = new Set<string>();
    const dedupedSections = parsed.sections.filter((s) => {
      const key = s.text.trim().toLowerCase();
      if (!key) return false;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
    const limitedSections = dedupedSections.slice(0, 5);

    const highSections = limitedSections.filter(
      (s) => s.aiLikelihood === "HIGH"
    ).length;
    const mediumSections = limitedSections.filter(
      (s) => s.aiLikelihood === "MEDIUM"
    ).length;

    let calibrated = parsed.aiProbability;
    if (highSections >= 3) calibrated = Math.max(calibrated, 0.9);
    else if (highSections >= 1 && mediumSections >= 1)
      calibrated = Math.max(calibrated, 0.75);
    else if (highSections >= 1) calibrated = Math.max(calibrated, 0.7);
    else if (mediumSections >= 2) calibrated = Math.max(calibrated, 0.55);

    calibrated = Math.min(Math.max(calibrated, 0), 1);

    let finalLevel: DetectionResult["level"];
    if (calibrated <= 0.25) finalLevel = "LOW";
    else if (calibrated <= 0.6) finalLevel = "MEDIUM";
    else finalLevel = "HIGH";

    const output: DetectionResult = {
      ...parsed,
      aiProbability: calibrated,
      level: finalLevel,
      sections: limitedSections,
    };

    return NextResponse.json(output);
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "AI detection failed" },
      { status: 500 }
    );
  }
}